### ISSUE TITLE
Output or capture errors during failed installs

### ISSUE THREAD

**Issue by avishnyakov** [shurick81/Dynamics365Configuration#18]
It would be nice if this module could output or capture errors during the installation process.

Currently, install process fails without explanation:
```
Installation job finished but the product is still not installed. Current product version installed is 'Could not load 
    crm: Microsoft.Crm.PowerShell PSSnapin'
```

It can be improved in various ways:

* capturing errors from the install log file, and then outputting them into the console in case of failure
```
$path = "install-log-path"
Get-Content $path | Select-String -Pattern "Error" -SimpleMatch
```

* providing a variable in Install-Dynamics365Server where to save the logs
That way, install scripts can know about the installation log file and process it in case of failure.

Finally, Install-Dynamics365Server behaviour on failure should be known:
* is it non-0 return value?
* is it an exception?

**Comment by shurick81** [comment]
What was the question about "behaviour on failure"`? Was not it enough to throw an exception? https://github.com/shurick81/Dynamics365Configuration/blob/72120aba483e4705cc07f7ca1211af2cf16f6357/src/Dynamics365Configuration/Install-Dynamics365Server.psm1#L339. Then you can use try catch and exit in tests: https://github.com/shurick81/Dynamics365Configuration/blob/72120aba483e4705cc07f7ca1211af2cf16f6357/tests/Provision.ps1#L38-L65

**Comment by avishnyakov** [comment]
Exception is good enough, we can close this, then.
